### ISSUE TITLE
Provide a docker container

### ISSUE THREAD

**Issue by afedynitch** [impy-project/impy#14]
The compilation might be not trivial on some systems. A docker container that packages impy could be useful to provide through CI.

**Comment by HDembinski** [comment]
Yes, please!

**Comment by afedynitch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Technical issues](https://trello.com/c/IDUDscTc/5-technical-issues)

**Comment by HDembinski** [comment]
I am working on this and will provide a dockerfile for the repo.

**Comment by HDembinski** [comment]
I think we do not need this anymore, should we close this?

**Comment by afedynitch** [comment]
Sure
