### ISSUE TITLE
Add pre-commit and use black formatter

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#16]
pre-commit is a tool to enforce coding standards on a repository. It runs a few quick tests whenever a developer locally attempts to `git commit`.

pre-commit automatically ensures that new code that is committed is formatted according to the guidelines of the project. When several people are working the same project, this is extremely useful. For example, my editor is configured to use apply the `black` formatter automatically to Python code.

This project is currently not black-formatted, so when I try to patch something, the patch gets blown up by whitespace changes. Rather than disabling black individually for this project, I propose to follow the masses (all scikit-hep projects use black, as do many many other projects) and also auto-format with black.

I will set up a pre-commit configuration. It also automatically applies the flake8 linter, which works very well. It does not generate false positives, but finds a lot of annoyances and clutter, like variables that are imported but not used.

**Comment by afedynitch** [comment]
I also use black for everything. For me it’s fine. @jncots ?

**Comment by jncots** [comment]
I like the suggestion. I am for it.

**Comment by HDembinski** [comment]
@afedynitch @jncots ok great. I just tried to add pre-commit to the repo. It seemed to work, but I am not sure whether it succeeded. I may not have the rights to add web services.

If you are not familiar with pre-commit, it is a tool to run other tools on new commits before they are submitted. You install it locally (pip install pre-commit). For each repository, you need to install the pre-commit hooks once (do pre-commit install in the repo). From then on, pre-commit will run fast check on every commit, before it is submitted, and stop the commit if the checks fail. Additionally, it installs a service on Github which runs the same checks on every commit/PR.

This way, it is ensured that new code added is always formatted correctly and linted and whatever else you can check automatically. We should start by adding just a formatter to pre-commit, and later add flake8 as a linter.

**Comment by afedynitch** [comment]
Thanks!!

I have seen the notification and gave permission to the service. Is anything else needed to make it work? Do I need to make an installation locally as well, if it is enabled on github?

**Comment by HDembinski** [comment]
It seems to work, see my new PR! :)
