### ISSUE TITLE
Build problems if multiple compilers installed

### ISSUE THREAD

**Issue by afedynitch** [impy-project/impy#23]
In some cases the build doesn't complete for some of the models. The issues is not regular and can occur for some configs.

What seems to happen is that `make` interferes with how numpy or f2py enumerate their paths. So this is more of a search and collecting thoughts.

If the build fails, then the inspection of the "f2l" logs gives something like:
```
error: Command "/usr/bin/gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/opt/miniconda3/lib -Wl,-rpath-link,/opt/miniconda3/lib -L/opt/miniconda3/lib /tmp/tmp94uj2d4_/tmp/tmp94uj2d4_/src.linux-x86_64-3.8/eposlhcmodule.o /tmp/tmp94uj2d4_/tmp/tmp94uj2d4_/src.linux-x86_64-3.8/fortranobject.o /tmp/tmp94uj2d4_/tmp/tmp94uj2d4_/src.linux-x86_64-3.8/eposlhc-f2pywrappers.o sources/epos-con-lhc.o sources/epos-uti-lhc.o sources/epos-xan-lhc.o sources/epos-jps-lhc.o sources/epos_interface.o sources/epos-qsh-lhc.o sources/epos-dro-lhc.o sources/epos-tim-lhc.o sources/epos-sem-lhc.o sources/epos-rsh-lhc.o sources/epos-xpr-lhc.o sources/epos_j.o sources/epos-bas-lhc.o sources/epos-fra-lhc.o sources/epos-int-lhc.o sources/epos-hnb-lhc.o sources/epos-random.o sources/epos-ids-lhc.o sources/epos-ico-lhc.o sources/eposm.o sources/epos-dky-lhc.o sources/epos-par-lhc.o sources/epos-ems-lhc.o sources/epos-omg-lhc.o /home/afedyni/devel/impy/src/logging.o -L/usr/lib/gcc/x86_64-linux-gnu/10 -L/usr/lib/gcc/x86_64-linux-gnu/10 -lgfortran -o ./eposlhc.cpython-38-x86_64-linux-gnu.so" failed with exit status 1
```
Repeating the command in the subfolder reveals the true error:
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
Some of the libs build though. Inspecting `impy/lib` shows that f2py links to the wrong fortran libs from conda rather than that of gfortran-10:
```
(base) afedyni@thrvm1:~/devel/impy/impy/lib$ ldd sophia.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffc14f46000)
        libgfortran.so.4 => /opt/miniconda3/lib/libgfortran.so.4 (0x00007f424c99d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f424c82e000)
        libgcc_s.so.1 => /opt/miniconda3/lib/libgcc_s.so.1 (0x00007f424c81a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f424c628000)
        libquadmath.so.0 => /opt/miniconda3/lib/libquadmath.so.0 (0x00007f424c5ee000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f424cd92000)
```

Moving to a fresh conda environment, without gfortran libs installed allows the build to succeed:
```
(fresh) afedyni@thrvm1:~/devel/impy/impy/lib$ ldd sophia.cpython-38-x86_64-linux-gnu.so 
        linux-vdso.so.1 (0x00007ffdb9be8000)
        libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f5b6ff48000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5b6fdf9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5b6fdde000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5b6fbec000)
        libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f5b6fba2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5b7050a000)
```

Note that this might not be solution to other build issues. There is also one other issue #11, which is related to the newer f2py failing to export all the symbols to the python namespace. Which is also a mystery, still.

**Comment by jncots** [comment]
I guess the compilation of *.o object files is done with gcc gfortran which requires the dynamic library `/usr/lib/gcc/x86_64-linux-gnu/10/libgfortran.so`. However, when the f2py links the files it uses the library `-lgfortran` (which is short for `libgfortran.so`)  which is located in `/opt/miniconda3/lib` because the option `-L/opt/miniconda3/lib` for directories search is the met first in the list of options, although `-L/usr/lib/gcc/x86_64-linux-gnu/10` options should be used. So, when there is no installed gfortran library in `/opt/miniconda3/lib`, the linker finds right dynamic library at `-L/usr/lib/gcc/x86_64-linux-gnu/10`.

**Comment by HDembinski** [comment]
@afedynitch I am currrently trying again to build impy in a docker image.

I am using this image, which is a standard image which we use to build our Scikit-HEP wheels on Linux.

quay.io/pypa/manylinux2010_x86_64:latest

I am also getting errors there when I run `make -j8`. Can we please first try to get the build stable on this image? Using the image makes sure we have exactly the same environment.

**Comment by jncots** [comment]
What concerns the output of `ldd sophia.cpython-38-x86_64-linux-gnu.so` the wrong library is written in the *.so file by the option `-Wl,-rpath,/opt/miniconda3/lib` which writes down the directories to search for required dynamic libraries.

**Comment by HDembinski** [comment]
Ok, my failures are relate to the fact that neither `make clean` nor `make distclean` remove all object files. Sorry, but building impy is a nightmare.

**Comment by HDembinski** [comment]
We shouldn't try to make impy compile on every user's system. Instead we should build binary wheels centrally for every release with cibuildwheels. Then we only need to make it work reliably in the docker images that cibuildwheels uses.

**Comment by jncots** [comment]
I think this could work https://stackoverflow.com/a/54202764

**Comment by jncots** [comment]
To solve the issue with wrong search paths I would try to add option

`--f90flags="-L/usr/lib/gcc/x86_64-linux-gnu/10"`
to command

eposlhc.pyf: sources/epos-bas-lhc.f sources/epos_interface.f Makefile
	$(F2PY) -m eposlhc -h eposlhc.pyf --overwrite-signature only: $(EPOS_FUNC) : sources$(PATHSEP)epos-bas-lhc.f sources$(PATHSEP)epos-ids-lhc.f sources$(PATHSEP)epos_interface.f $(LOGS) > epos-lhc.f2l 2>&1

in Makefile.

To solve the problem with wrong paths written in dynamic library probably 

```bash
export LDFLAGS=-Wl,-rpath=-L/usr/lib/gcc/x86_64-linux-gnu/10
```
can help

**Comment by afedynitch** [comment]
OK. Let's try building it on manylinux! It was actually building fine for 10 years or so on most systems. Only lately (~2-3 years) it became more difficult due to the many environments.

Exporting flags is can not be a permanent solution.
