### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#28]
Running `python -m pytest impy/tests` shows 5 failing tests.

```
ERROR tests/test_decay_afterburner.py
ERROR tests/test_event_generator.py
ERROR tests/test_new_interface.py
ERROR tests/test_sibyll.py - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
ERROR tests/test_urqmd.py
```

Could someone look into this? I will add some CI to check these tests automatically so that we will detect these issues automatically in the future.

**Comment by HDembinski** [comment]
I went through the tests and I am now very concerned about the state of impy. Not only do the tests not work. I am getting segfaults, hangups, and shutdowns of the python interpreter (when any SIBYLL version is used).

**Comment by afedynitch** [comment]
Indeed, the tests are not well maintained and need to be changed anyways now after all the interface changes.

The most important test for checking the consistent compilation of event generators is the random number sequence conservations. For the tests the models have to be initialized with the same seed. Then after 10 or N events, the random number generator state has to be exactly the same as in all runs. This test has the same depth as checking each event one by one.

Obviously for something like this to run consistently, each generator should use the random numbers from rangen.f of impy. For some models, like EPOS and PYTHIA this is not yet done.

**Comment by HDembinski** [comment]
I am closing this, since it seems outdated.
