### ISSUE TITLE
impy_config needs to go

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#31]
impy_config is used as a modifiable global state that is used in several places. This is bad, because changing impy_config in some place can have unexpected side-effects elsewhere. It introduces a hidden coupling of all classes to each other, which is impossible for an outsider to understand. This bad pattern is why ROOT is such a pain to work with, and goes against the principles of OOP.

Instead of a global config that is shared between all models, each model should accept its own configuration in the `__init__`. It is then up the user whether they want to use the same config instance for two models or different independent instances.

**Comment by HDembinski** [comment]
Python has keyword arguments, which allows one to pass configuration and set default values in an elegant way. This is how professional libraries like matplotlib do it.

Pseudo-code
```py
class Sibyll:
    def __init__(self, event_kinematics, *, debug_level=0, foo_or_bar="foo", ...):
```

**Comment by afedynitch** [comment]
The motivation behind a global state is that if one tries to debug something physics wise, one needs to be able to switch on and off debugging info for some specific events or change some parameters globally, like the condition for stable particles. So a global shared state is kinda intended.

For the generator specific settings there is no need for a global shared state, but then each specific setting needs a doc or a setter/getter. These are probably very few items, though.

We can consider moving this forward but I recommend going for this issue after the updated API is stable and some more urgent technical issues are fixed.

**Comment by HDembinski** [comment]
Yes, let's postpone this, but I want to clarify one point. I am just against having a **single global dict**. I am ok with each model having its own local dict, which ideally should be attached to the model instance, but since we can only generate a single instance of each model anyway, it can also be attached to the class.

 I think it is fine that each generator has a flexible dict with configurations, which is for advanced usage and there is no API provided for changing this dict. My concern is only the coupling which this global state creates between all models in the library.

**Comment by afedynitch** [comment]
I agree that it has to go. There now already a design issue with a global config when looking at #43 where it would actually result in faulty behavior if one would initialize a model with `FixedTarget` and then a different one with `CenterOfMass`. The first frame would be overwritten by center of mass.

In fact there is only a very small list of arguments that would need some sort of global setting, if any. It needs some thoughts though.

**Comment by HDembinski** [comment]
I plan to work on this, because I have a very clear plan in my mind how to remove impy_config without restricting the opportunities it offers.

Briefly: the configuration options in impy_config will become fields of the MCRun base class, so that they are specific to the generator instance. We further make MCRun a singleton so that only one instance can exist per process.
