### ISSUE TITLE
Check and unify the random number generators

### ISSUE THREAD

**Issue by afedynitch** [impy-project/impy#44]
The random number generators should be the same for all the models. For most of the models this is already done, but for some, like EPOS, Pythia and UrQMD it's not. This has to be verified and implemented where necessary.

From that point one can design the crucial random number sequence conservation tests.

**Comment by HDembinski** [comment]
Why is this necessary? If there is some weird quirk in the random number generator that changes the physics output, then we should make sure to use the original random number generator that is used during tuning and in CORSIKA.

**Comment by afedynitch** [comment]
That's what CORSIKA does. It uses it's own random number generator for all models. Because some models like PYTHIA6 use simplistic generators that don't survive moving from one to another architecture. IMPY uses the CORSIKA generator RMMARD.

Using different generators will add another maintenance burden if the random number sequence is not conserved on different compilers/machine archs.

**Comment by HDembinski** [comment]
Ok, if CORSIKA also does it like this, then we should do, too, fair enough! Thanks for explaining.

**Comment by afedynitch** [comment]
Cheers!
If the tests relying on random number sequence fail, they all will fail. So this will be easier to catch.
