### ISSUE TITLE
Possible workaround for the multiple initialization issue

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#46]
AFAIU, the multiple initialization issue only exists for those DPMJet and Phojet versions which use the same Fortran module. The initialization issue is annoying and difficult to hide from the users (but it should be hidden).

I think we can work around this limitation by building separate fortran modules for phojet. The phojet modules would be built identically to the dpmjet ones, but use a different module name.

**Comment by afedynitch** [comment]
In fact it’s very easy to build separately the PHOJET libs by simply avoiding linking with the DPMJET object files. But, we would need to have individual PYFs and interfaces for these then. @HDembinski, you mentioned that you rebuilt the pyfs after I rebuilt and committed the files  How did you do it? CMake or Makefiles?

**Comment by HDembinski** [comment]
You can build new pyf files with CMake simply by commenting them out in the call to `f2py_add_module` under `SOURCES`. If they are not listed there, they are generated on the fly.

**Comment by HDembinski** [comment]
But I think we only have to take the existing dpmjet pyf and rename the module in the pyf file.

**Comment by afedynitch** [comment]
That's one option. The other one is have a clean PHOJET pyf because DPMJET is calling phojet functions but phojet never calls functions from DPMJET sources. The *.f's would not require recompilation. Is this possible to reuse the *.f.o from the DPMJET sources without a bit redesign of the F2Py cmake function?

**Comment by HDembinski** [comment]
Sure, all fortran source files are only compiled once.

**Comment by afedynitch** [comment]
Will be fixed together with #55
