### ISSUE TITLE
Diffraction missing in Pythia6?

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#56]
I showed this plot to my colleague Michael Schmelling:

![output](https://user-images.githubusercontent.com/2631586/185932757-829cfe11-e3d5-4b9b-a2ff-ab73ce50c76a.png)

Pythia6 looks different in the protons at |x| ~ 1. I assume this is due to differences in diffraction. Pythia6 maybe does not have diffraction included in the model, but Michael said it does, but perhaps it is deactivated. @afedynitch Do you know whether this is a bug or intended?

**Comment by afedynitch** [comment]
Switched to full minimum-bias mode by default. See MSEL=2 on page 227 of [the bible](https://arxiv.org/abs/hep-ph/0603175). Committed to #54, which will close this issue.
