### ISSUE TITLE
Provide a function find_model(string)

### ISSUE THREAD

**Issue by afedynitch** [impy-project/impy#69]
In the past we had the models indexed by strings. Now we moved to derived classes and the problem is that the capitalization style is not uniform contrary to the previous version. To have simpler applications it would be nice to have a function in `__init__.py` of `impy.models` which returns the class given a string without requiring specific capitalization. E.g. `find_model('sIbYlL23d') should return the class `impy.models.Sibyll23d`.

**Comment by HDembinski** [comment]
I am not a fan of adding this back to impy, because it creates more than one way to do things (model lookup). I think user code can be expected to write something like this:

```py
lookup = {}
for model in dir(impy.models):
      lookup[model.__name__.lower()] = model

def get_model(model_name):
      return lookup[model_name.lower()]
```
If you add such functionality to impy, it creates more than one way to do it and that is a source of confusion and redundancy.

Perhaps that this and other recent requests are driven by the needs of MCVD, but I don't thikn that MCVD is the typical use case of imply.

**Comment by HDembinski** [comment]
If you nevertheless think this should be in impy, then it could be placed into a `tools` submodule.
```py
from impy.tools import get_model_by_name
```

**Comment by afedynitch** [comment]
Right now the workaround is a bit more awkward because even if you know the name as string it requires something like this to work with it `mod_class = getattr(importlib.import_module("impy.models"), "Sibyll23d")`, after that loop. So putting something like this into tools sounds like a viable solution.

**Comment by HDembinski** [comment]
You are right, but with `getattr` it is not much more complicated to write:

```py
import impy.models

lookup = {}
for model_name in dir(impy.models):
      lookup[model.lower()] = getattr(impy.models, model)

def get_model(model_name):
      return lookup[model_name.lower()]
```

**Comment by afedynitch** [comment]
Hmm. Actually true. I can put it in the corresponding `tools` modules of my tools (m2m, MCVD, MCEq related stuff). It's a longer list but not a big deal.

Thanks for discussion.
