### ISSUE TITLE
Use scipy.constants instead of own constants?

### ISSUE THREAD

**Issue by HDembinski** [impy-project/impy#9]
Consider replacing `impy.constants` with `scipy.constants`, which has useful things like the proton mass, and also has units.
https://docs.scipy.org/doc/scipy/reference/constants.html

While one should not depend on too many other packages, depending on well-maintained foundational packages like numpy or scipy is desirable and better than to roll your own code. Even code that you can write yourself quickly is going to be a burden in the long run, since you have to test everything and document everything. This should be outsourced as much as possible.

Potential drawback: scipy.constants is the full SI unit system, not the Heaviside system when hbar and c are 1.

**Comment by HDembinski** [comment]
Another drawback: I think "TeV" is not defined...

**Comment by afedynitch** [comment]
Another alternative is to skip all these TeV and PeV definitions and use by default GeV, cm, and s. In the end the code is not that complex to require a full unit system.

**Comment by HDembinski** [comment]
Sure, you can do that, but the system changes from field to field and package to package, which is annoying and confusing. That's the reasoning behind making the units visible instead of implicit, which is good, it makes the code immediately readable for everyone. Also, there is no universally accepted convention. You may think it is GeV and cm, but the LHCb software uses MeV and mm interally, for example. It is annoying to remember which system is applied where.

**Comment by HDembinski** [comment]
Ok, let me step back here for a moment from what I wrote before.

After thinking some more, offering your own units makes sense if you can it so that the definitions of the units reflect the internal units used in the generators. You want to avoid converting the raw numbers provided by the generator just so that they conform to an external unit system. In other words, if you followed my initial proposal, you would have to scale all energies and momenta and lengths so that they are in the base units used by scipy. This is not efficient. 

Do all generators using the same units? If so, great, then define `TeV` in terms of those units.

**Comment by afedynitch** [comment]
The only constant introducing a scipy dependency is the speed of light? We can put it by hand from [here](https://github.com/scipy/scipy/blob/8a64c938ddf1ae4c02a08d2c5e38daeb8d061d38/scipy/constants/_codata.py) and remove scipy from the deps?

**Comment by HDembinski** [comment]
Yes, I now think we should use our own unit system. I think you cannot drop scipy that easily, though.

qgsjet.py: `from scipy.interpolate import UnivariateSpline`

I don't recommend to implement a custom spline interpolator, this is challenging.

**Comment by HDembinski** [comment]
I think this can be closed.
